spring:
  datasource:
    url: jdbc:mysql://localhost:3308/system?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cdy0826
    password: mid@sit12#$
